# Generated by Django 5.2.7 on 2025-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_name_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_images',
            field=models.JSONField(blank=True, default=list, verbose_name='详情图URL列表'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='主图URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='规格参数'),
        ),
    ]
