# Generated by Django 5.2.7 on 2025-11-05 09:23

import catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_category_level_category_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(storage=catalog.storage.LocalMediaStorage(), upload_to='images/%Y/%m/%d/', verbose_name='图片文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原文件名')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='内容类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
            },
        ),
    ]
