# Generated by Django 5.2.7 on 2025-11-15 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_product_stats_and_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('lock', '锁定'), ('release', '释放'), ('adjust', '调整')], max_length=20, verbose_name='变更类型')),
                ('quantity', models.IntegerField(verbose_name='变更数量')),
                ('reason', models.CharField(max_length=100, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='catalog.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存日志',
                'verbose_name_plural': '库存日志',
                'indexes': [models.Index(fields=['product', 'created_at'], name='catalog_inv_product_55e4e1_idx'), models.Index(fields=['change_type'], name='catalog_inv_change__9a36ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'indexes': [models.Index(fields=['user', 'created_at'], name='catalog_pro_user_id_b5474d_idx'), models.Index(fields=['product'], name='catalog_pro_product_7cdd28_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(db_index=True, max_length=200, verbose_name='搜索关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索日志',
                'verbose_name_plural': '搜索日志',
                'indexes': [models.Index(fields=['keyword', '-created_at'], name='catalog_sea_keyword_423038_idx'), models.Index(fields=['user', 'created_at'], name='catalog_sea_user_id_a7c956_idx')],
            },
        ),
    ]
