# Generated by Django 5.2.7 on 2025-11-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_extend_brand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, help_text='商品来源供应商', max_length=50, null=True, verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_code',
            field=models.CharField(blank=True, help_text='供应商系统中的商品代码', max_length=100, null=True, verbose_name='供应商商品代码'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='content_type',
            field=models.CharField(blank=True, help_text='检测到的MIME类型', max_length=100, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='original_name',
            field=models.CharField(blank=True, help_text='用户上传时的原始文件名', max_length=255, verbose_name='原文件名'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='size',
            field=models.PositiveIntegerField(default=0, help_text='文件大小（字节）', verbose_name='文件大小'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('supplier', 'supplier_code')},
        ),
        migrations.AddIndex(
            model_name='mediaimage',
            index=models.Index(fields=['-created_at'], name='catalog_med_created_c7a328_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaimage',
            index=models.Index(fields=['content_type'], name='catalog_med_content_3d27bf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier', 'supplier_code'], name='catalog_pro_supplie_a2ccdc_idx'),
        ),
    ]
