# Generated by Django 5.2.7 on 2025-11-18 08:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_supplier_product_supplier_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order', 'id'], 'verbose_name': '品牌', 'verbose_name_plural': '品牌'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'ordering': ['-created_at'], 'verbose_name': '库存日志', 'verbose_name_plural': '库存日志'},
        ),
        migrations.AlterModelOptions(
            name='mediaimage',
            options={'ordering': ['-created_at'], 'verbose_name': '媒体图片', 'verbose_name_plural': '媒体图片'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='productfavorite',
            options={'ordering': ['-created_at'], 'verbose_name': '商品收藏', 'verbose_name_plural': '商品收藏'},
        ),
        migrations.AlterModelOptions(
            name='searchlog',
            options={'ordering': ['-created_at'], 'verbose_name': '搜索日志', 'verbose_name_plural': '搜索日志'},
        ),
        migrations.RemoveIndex(
            model_name='mediaimage',
            name='catalog_med_content_3d27bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_is_acti_ed6a39_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_price_2d2a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_sales_c_9ac6ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_supplie_a2ccdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='productfavorite',
            name='catalog_pro_user_id_b5474d_idx',
        ),
        migrations.RemoveIndex(
            model_name='productfavorite',
            name='catalog_pro_product_7cdd28_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchlog',
            name='catalog_sea_user_id_a7c956_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='品牌Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='默认分类', max_length=100, unique=True, verbose_name='类别名称'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='file',
            field=models.FileField(upload_to='images/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_images',
            field=models.JSONField(blank=True, default=list, verbose_name='详情图列表'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_images',
            field=models.JSONField(blank=True, default=list, verbose_name='主图列表'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='销售数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='productfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='搜索时间'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='keyword',
            field=models.CharField(max_length=200, verbose_name='搜索关键词'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-sales_count'], name='catalog_pro_is_acti_93f887_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-view_count'], name='catalog_pro_is_acti_1e9dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
        migrations.AddIndex(
            model_name='productfavorite',
            index=models.Index(fields=['user', '-created_at'], name='catalog_pro_user_id_371008_idx'),
        ),
        migrations.AddIndex(
            model_name='productfavorite',
            index=models.Index(fields=['product', '-created_at'], name='catalog_pro_product_60535c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', '-created_at'], name='catalog_sea_user_id_fe3765_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['-created_at'], name='catalog_sea_created_c65b25_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_code',
        ),
    ]
