# Generated by Django 5.2.7 on 2025-11-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFavorite',
        ),
    ]
