# Generated by Django 5.2.7 on 2025-11-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_delete_productfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='invoice_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='开票价'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sales',
            field=models.CharField(default='1', max_length=1, verbose_name='海尔是否可采(1可采,0不可采)'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市场价'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_sales_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='不可采原因'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='海尔产品编码'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='海尔产品组'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='海尔主图URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='海尔产品型号'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_page_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='海尔拉页URL列表'),
        ),
        migrations.AddField(
            model_name='product',
            name='rebate_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='台返'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_rebate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='直扣'),
        ),
        migrations.AddField(
            model_name='product',
            name='supply_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='普通供价'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='库位编码'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_grade',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='仓库等级(0本级仓/1上级仓)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='catalog_pro_product_ac7085_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_sales'], name='catalog_pro_is_sale_6a3584_idx'),
        ),
    ]
