# Generated by Django 5.2.7 on 2025-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_invoice_price_product_is_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('local', '本地商品'), ('haier', '海尔商品')], default='local', help_text='local=本地维护商品; haier=来自海尔API的商品', max_length=20, verbose_name='商品来源'),
        ),
    ]
