# Generated by Django 5.2.7 on 2025-12-02 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='标题')),
                ('link_url', models.URLField(blank=True, default='', max_length=500, verbose_name='跳转链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='catalog.mediaimage', verbose_name='图片')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'ordering': ['order', '-id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='catalog_hom_is_acti_d11f0e_idx')],
            },
        ),
    ]
