# Generated by Django 5.2.7 on 2025-12-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='分类Logo'),
        ),
    ]
