# Generated by Django 5.2.7 on 2025-12-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('major', '大类'), ('minor', '小类')], default='major', max_length=10, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='父类别'),
        ),
    ]
