# Generated by Django 5.2.7 on 2025-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_category_level_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.CharField(choices=[('major', '品类'), ('minor', '子品类'), ('item', '品项')], default='major', max_length=10, verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='默认分类', max_length=100, verbose_name='类别名称'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('level', 'name'), name='unique_category_level_name'),
        ),
    ]
