# Generated by Django 5.2.7 on 2025-12-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_category_parent_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='catalog.mediaimage', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='catalog.product', verbose_name='商品'),
        ),
    ]
