# Generated by Django 5.2.7 on 2025-02-07 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_homebanner_image_alter_inventorylog_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='SKU名称')),
                ('sku_code', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU编码')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='规格参数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='售价')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('image', models.URLField(blank=True, default='', max_length=500, verbose_name='SKU主图')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
            },
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='catalog.productsku', verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['sku', 'created_at'], name='catalog_inv_sku_id_539bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pro_product_3f7cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['sku_code'], name='catalog_pro_sku_cod_73b5b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsku',
            unique_together={('product', 'sku_code')},
        ),
    ]
