# Generated by Django 5.2.7 on 2025-12-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_productsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '案例',
                'verbose_name_plural': '案例',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseDetailBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('text', '文本'), ('image', '图片')], default='text', max_length=10, verbose_name='类型')),
                ('text', models.TextField(blank=True, default='', verbose_name='文本内容')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '案例详情块',
                'verbose_name_plural': '案例详情块',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='inventorylog',
            new_name='catalog_inv_sku_id_b95c3a_idx',
            old_name='catalog_inv_sku_id_539bf8_idx',
        ),
        migrations.RenameIndex(
            model_name='productsku',
            new_name='catalog_pro_product_1a6f89_idx',
            old_name='catalog_pro_product_3f7cc5_idx',
        ),
        migrations.RenameIndex(
            model_name='productsku',
            new_name='catalog_pro_sku_cod_41bb6e_idx',
            old_name='catalog_pro_sku_cod_73b5b9_idx',
        ),
        migrations.AddField(
            model_name='case',
            name='cover_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_as_cover', to='catalog.mediaimage', verbose_name='展示图'),
        ),
        migrations.AddField(
            model_name='casedetailblock',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_blocks', to='catalog.case', verbose_name='案例'),
        ),
        migrations.AddField(
            model_name='casedetailblock',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_detail_blocks', to='catalog.mediaimage', verbose_name='图片'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['is_active', 'order'], name='catalog_cas_is_acti_647a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='casedetailblock',
            index=models.Index(fields=['case', 'order', 'id'], name='catalog_cas_case_id_376940_idx'),
        ),
    ]
