# Generated by Django 5.2.7 on 2025-12-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_category_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='position',
            field=models.CharField(choices=[('home', '首页'), ('gift', '礼品专区'), ('designer', '设计师专区')], default='home', max_length=20, verbose_name='展示位置'),
        ),
        migrations.AddIndex(
            model_name='homebanner',
            index=models.Index(fields=['position', 'is_active', 'order'], name='catalog_hom_positio_8edef4_idx'),
        ),
    ]
