# Generated by Django 5.2.7 on 2025-12-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_homebanner_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialZone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('gift', '礼品专区'), ('designer', '设计师专区')], default='gift', max_length=20, verbose_name='专区类型')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='副标题')),
                ('link_url', models.URLField(blank=True, default='', max_length=500, verbose_name='跳转链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_zones', to='catalog.mediaimage', verbose_name='图片')),
            ],
            options={
                'verbose_name': '首页专区',
                'verbose_name_plural': '首页专区',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='specialzone',
            index=models.Index(fields=['type', 'is_active', 'order'], name='catalog_spe_type_is__7a6253_idx'),
        ),
    ]
