# Generated by Django 5.2.7 on 2025-12-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_special_zone_cover'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='specialzonecover',
            name='catalog_spe_type_is__57a37b_idx',
        ),
        migrations.RemoveField(
            model_name='specialzonecover',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='specialzonecover',
            name='order',
        ),
        migrations.RemoveField(
            model_name='specialzonecover',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='specialzonecover',
            name='title',
        ),
        migrations.AlterField(
            model_name='specialzonecover',
            name='type',
            field=models.CharField(choices=[('gift', '礼品专区'), ('designer', '设计师专区')], default='gift', max_length=20, unique=True, verbose_name='专区类型'),
        ),
        migrations.AlterModelOptions(
            name='specialzonecover',
            options={'ordering': ['type'], 'verbose_name': '首页专区图片', 'verbose_name_plural': '首页专区图片'},
        ),
        migrations.AddIndex(
            model_name='specialzonecover',
            index=models.Index(fields=['type', 'is_active'], name='catalog_spe_type_is__9f3a2d_idx'),
        ),
    ]
