# Generated by Django 5.2.7 on 2025-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_special_zone_cover_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_designer_zone',
            field=models.BooleanField(default=False, verbose_name='设计师专区展示'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_gift_zone',
            field=models.BooleanField(default=False, verbose_name='礼品专区展示'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_in_gift_zone', 'is_active'], name='catalog_pro_show_in_01716a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_in_designer_zone', 'is_active'], name='catalog_pro_show_in_291623_idx'),
        ),
    ]
