# Generated by Django 5.2.7 on 2026-02-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_remove_productsku_dealer_price'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_show_in_e2ccfe_idx',
            old_name='catalog_pro_show_in_01716a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_show_in_8de046_idx',
            old_name='catalog_pro_show_in_291623_idx',
        ),
        migrations.RenameIndex(
            model_name='specialzonecover',
            new_name='catalog_spe_type_7c2f53_idx',
            old_name='catalog_spe_type_is__9f3a2d_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('', '无标签'), ('brand_direct', '品牌直发'), ('source_factory', '源头厂家')], default='', max_length=20, verbose_name='商品标签'),
        ),
    ]
