# Generated by Django 5.2.7 on 2026-02-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_rename_catalog_pro_show_in_01716a_idx_catalog_pro_show_in_e2ccfe_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_best_seller_zone',
            field=models.BooleanField(default=False, verbose_name='爆品专区展示'),
        ),
        migrations.AlterField(
            model_name='specialzonecover',
            name='type',
            field=models.CharField(choices=[('gift', '礼品专区'), ('designer', '设计师专区'), ('best_seller', '爆品专区')], default='gift', max_length=20, unique=True, verbose_name='专区类型'),
        ),
    ]
