# Generated by Django 5.2.7 on 2026-02-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_product_show_in_best_seller_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='position',
            field=models.CharField(choices=[('home', '首页'), ('gift', '礼品专区'), ('designer', '设计师专区'), ('best_seller', '爆品专区')], default='home', max_length=20, verbose_name='展示位置'),
        ),
    ]
