# Generated by Django 5.2.7 on 2026-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_homebanner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_promotion_zone',
            field=models.BooleanField(default=False, verbose_name='优惠专区展示'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='position',
            field=models.CharField(choices=[('home', '首页'), ('gift', '礼品专区'), ('designer', '设计师专区'), ('best_seller', '爆品专区'), ('promotion', '优惠专区')], default='home', max_length=20, verbose_name='展示位置'),
        ),
        migrations.AlterField(
            model_name='specialzonecover',
            name='type',
            field=models.CharField(choices=[('gift', '礼品专区'), ('designer', '设计师专区'), ('best_seller', '爆品专区'), ('promotion', '优惠专区')], default='gift', max_length=20, unique=True, verbose_name='专区类型'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_in_promotion_zone', 'is_active'], name='catalog_pro_show_in_21ca3b_idx'),
        ),
    ]
