# Generated by Django 5.2.7 on 2026-05-05 04:39

import django.db.models.deletion
import stores.models
from django.db import migrations, models


def remove_category_unique_constraint(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    constraint_name = 'unique_category_level_parent_name'
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE %s DROP CONSTRAINT IF EXISTS %s'
            % (
                schema_editor.quote_name(Category._meta.db_table),
                schema_editor.quote_name(constraint_name),
            )
        )
        schema_editor.execute(
            'DROP INDEX IF EXISTS %s' % schema_editor.quote_name(constraint_name)
        )
        return

    constraint = models.UniqueConstraint(
        fields=('level', 'parent', 'name'),
        name=constraint_name,
    )
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor,
            Category._meta.db_table,
        )
    if constraint.name in constraints:
        schema_editor.remove_constraint(Category, constraint)


def restore_category_unique_constraint(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    constraint = models.UniqueConstraint(
        fields=('level', 'parent', 'name'),
        name='unique_category_level_parent_name',
    )
    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(
            cursor,
            Category._meta.db_table,
        )
    if constraint.name not in constraints:
        schema_editor.add_constraint(Category, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_product_show_in_promotion_zone_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    remove_category_unique_constraint,
                    reverse_code=restore_category_unique_constraint,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='category',
                    name='unique_category_level_parent_name',
                ),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(default=stores.models.get_main_store_pk, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=stores.models.get_main_store_pk, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='store',
            field=models.ForeignKey(default=stores.models.get_main_store_pk, on_delete=django.db.models.deletion.PROTECT, related_name='home_banners', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=stores.models.get_main_store_pk, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='specialzonecover',
            name='store',
            field=models.ForeignKey(default=stores.models.get_main_store_pk, on_delete=django.db.models.deletion.PROTECT, related_name='special_zone_covers', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='specialzonecover',
            name='type',
            field=models.CharField(choices=[('gift', '礼品专区'), ('designer', '设计师专区'), ('best_seller', '爆品专区'), ('promotion', '优惠专区')], default='gift', max_length=20, verbose_name='专区类型'),
        ),
        migrations.AddIndex(
            model_name='homebanner',
            index=models.Index(fields=['store', 'is_active', 'order'], name='catalog_hom_store_i_2f6661_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active'], name='catalog_pro_store_i_36fe43_idx'),
        ),
        migrations.AddIndex(
            model_name='specialzonecover',
            index=models.Index(fields=['store', 'type', 'is_active'], name='catalog_spe_store_i_07b54e_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_brand_store_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('store', 'level', 'parent', 'name'), name='unique_category_level_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='specialzonecover',
            constraint=models.UniqueConstraint(fields=('store', 'type'), name='unique_special_zone_cover_store_type'),
        ),
    ]
