# Generated by Django 5.2.7 on 2026-05-05 08:59

import django.db.models.deletion
import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_remove_category_unique_category_level_parent_name_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialZoneProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '动态专区商品',
                'verbose_name_plural': '动态专区商品',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialZone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='专区标题')),
                ('slug', models.SlugField(max_length=80, verbose_name='专区标识')),
                ('kind', models.CharField(choices=[('activity', '活动专区'), ('promotion', '优惠专区'), ('category', '品类专区'), ('brand', '品牌专区'), ('custom', '自定义专区')], default='activity', max_length=20, verbose_name='专区类型')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='副标题')),
                ('cover_image', models.URLField(blank=True, default='', max_length=500, verbose_name='封面图')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='首页展示')),
                ('home_order', models.IntegerField(default=0, verbose_name='首页排序')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(default=stores.models.get_main_store_pk, on_delete=django.db.models.deletion.PROTECT, related_name='special_zones', to='stores.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '动态运营专区',
                'verbose_name_plural': '动态运营专区',
                'ordering': ['home_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='homebanner',
            name='special_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_banners', to='catalog.specialzone', verbose_name='动态专区'),
        ),
        migrations.AddIndex(
            model_name='homebanner',
            index=models.Index(fields=['special_zone', 'is_active', 'order'], name='catalog_hom_special_c23499_idx'),
        ),
        migrations.AddField(
            model_name='specialzoneproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_zone_links', to='catalog.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='specialzoneproduct',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_products', to='catalog.specialzone', verbose_name='专区'),
        ),
        migrations.AddIndex(
            model_name='specialzone',
            index=models.Index(fields=['store', 'is_active', 'show_on_home', 'home_order'], name='catalog_spe_store_i_97bd19_idx'),
        ),
        migrations.AddIndex(
            model_name='specialzone',
            index=models.Index(fields=['store', 'kind'], name='catalog_spe_store_i_57ba84_idx'),
        ),
        migrations.AddIndex(
            model_name='specialzone',
            index=models.Index(fields=['start_at', 'end_at'], name='catalog_spe_start_a_dd56c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialzone',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='unique_special_zone_store_slug'),
        ),
        migrations.AddIndex(
            model_name='specialzoneproduct',
            index=models.Index(fields=['zone', 'is_active', 'order'], name='catalog_spe_zone_id_b48ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='specialzoneproduct',
            index=models.Index(fields=['product'], name='catalog_spe_product_21b8b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialzoneproduct',
            constraint=models.UniqueConstraint(fields=('zone', 'product'), name='unique_special_zone_product'),
        ),
    ]
