# Generated by Django 5.2.7 on 2026-05-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_specialzoneproduct_specialzone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='catalog.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='specialzoneproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_zone_links', to='catalog.product', verbose_name='商品'),
        ),
    ]
