# Generated by Django 5.2.7 on 2025-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_contact_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
