# Generated by Django 5.2.7 on 2025-11-02 11:16

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_name_alter_category_id'),
        ('orders', '0003_remove_order_address_order_snapshot_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.generate_order_number, max_length=100, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_address',
            field=models.TextField(default='', verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_contact_name',
            field=models.CharField(default='', max_length=50, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_phone',
            field=models.CharField(default='', max_length=20, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='购物车')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '购物车项',
                'verbose_name_plural': '购物车项',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
