# Generated by Django 5.2.7 on 2025-11-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('bank', '银行卡')], default='wechat', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('init', '待支付'), ('processing', '支付中'), ('succeeded', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('expired', '已过期')], default='init', max_length=20, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('logs', models.JSONField(blank=True, default=list, verbose_name='支付日志')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
            },
        ),
    ]
