# Generated by Django 5.2.7 on 2025-11-05 14:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_images_json'),
        ('orders', '0005_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='折扣金额')),
                ('effective_time', models.DateTimeField(verbose_name='生效时间')),
                ('expiration_time', models.DateTimeField(verbose_name='过期时间')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '折扣规则',
                'verbose_name_plural': '折扣规则',
            },
        ),
        migrations.CreateModel(
            name='DiscountTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='orders.discount', verbose_name='折扣')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_targets', to='catalog.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_targets', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '折扣适用范围',
                'verbose_name_plural': '折扣适用范围',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(related_name='product_discounts', through='orders.DiscountTarget', through_fields=('discount', 'product'), to='catalog.product', verbose_name='适用商品'),
        ),
        migrations.AddField(
            model_name='discount',
            name='users',
            field=models.ManyToManyField(related_name='user_discounts', through='orders.DiscountTarget', through_fields=('discount', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='适用用户'),
        ),
        migrations.AddIndex(
            model_name='discounttarget',
            index=models.Index(fields=['user', 'product'], name='orders_disc_user_id_3d6d19_idx'),
        ),
        migrations.AddIndex(
            model_name='discounttarget',
            index=models.Index(fields=['discount'], name='orders_disc_discoun_438464_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discounttarget',
            unique_together={('discount', 'user', 'product')},
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['effective_time', 'expiration_time'], name='orders_disc_effecti_5c4f53_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['priority'], name='orders_disc_priorit_71ec2e_idx'),
        ),
    ]
