# Generated by Django 5.2.7 on 2025-11-15 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_order_note_and_refund_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单状态历史',
                'verbose_name_plural': '订单状态历史',
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx'), models.Index(fields=['from_status', 'to_status'], name='orders_orde_from_st_6df65f_idx')],
            },
        ),
    ]
