# Generated by Django 5.2.7 on 2025-11-25 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_invoice_price_product_is_sales_and_more'),
        ('orders', '0008_add_order_status_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='取消原因'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_images',
            field=models.JSONField(blank=True, default=list, verbose_name='配送安装照片'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_record_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='发货单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='distribution_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配送时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='haier_order_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='海尔订单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='haier_so_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='海尔子订单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='haier_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='海尔订单状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='install_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='安装时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery_install',
            field=models.BooleanField(default=False, verbose_name='是否送装一体'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_government_order',
            field=models.BooleanField(default=False, verbose_name='是否国补订单'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='物流公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='物流单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='sn_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SN码'),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='市'),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_district',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_province',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='省'),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot_town',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='县/街道'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '待发货'), ('shipped', '待收货'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunding', '退款中'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['haier_order_no'], name='orders_orde_haier_o_3a4ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['haier_so_id'], name='orders_orde_haier_s_efee27_idx'),
        ),
    ]
