# Generated by Django 5.2.7 on 2025-11-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_actual_amount_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='haier_so_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='海尔子订单号'),
        ),
    ]
