# Generated by Django 5.2.7 on 2025-11-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_haier_so_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='发票抬头')),
                ('taxpayer_id', models.CharField(blank=True, default='', max_length=50, verbose_name='纳税人识别号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='接收邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='公司地址')),
                ('bank_account', models.CharField(blank=True, default='', max_length=100, verbose_name='开户行及账号')),
                ('invoice_type', models.CharField(choices=[('normal', '普通发票'), ('special', '专用发票')], default='normal', max_length=20, verbose_name='发票类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开票金额')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率(%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='税额')),
                ('status', models.CharField(choices=[('requested', '已申请'), ('issued', '已开具'), ('cancelled', '已取消')], default='requested', max_length=20, verbose_name='状态')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='发票号码')),
                ('file_url', models.URLField(blank=True, default='', verbose_name='发票文件URL')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='开具时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单发票',
                'verbose_name_plural': '订单发票',
                'indexes': [
                    models.Index(fields=['status'], name='orders_invo_status_4b6e6f_idx'),
                    models.Index(fields=['user', 'requested_at'], name='orders_invo_user_re_1a2b3c_idx'),
                ],
            },
        ),
    ]

