# Generated by Django 5.2.7 on 2025-11-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='orders_invo_status_b88bb2_idx',
            old_name='orders_invo_status_4b6e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='orders_invo_user_id_e025ed_idx',
            old_name='orders_invo_user_re_1a2b3c_idx',
        ),
    ]
