# Generated by Django 5.2.7 on 2025-12-01 00:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_orders_invo_status_4b6e6f_idx_orders_invo_status_b88bb2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('requested', '已申请'),
                            ('in_transit', '退货在途'),
                            ('received', '已收到退货'),
                            ('rejected', '已拒绝'),
                        ],
                        default='requested',
                        max_length=20,
                        verbose_name='状态',
                    ),
                ),
                ('reason', models.CharField(max_length=200, verbose_name='退货原因')),
                ('logistics_company', models.CharField(blank=True, default='', max_length=100, verbose_name='退货物流公司')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100, verbose_name='退货快递单号')),
                ('evidence_images', models.JSONField(blank=True, default=list, verbose_name='退货凭证图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processed_note', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                (
                    'order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='return_request',
                        to='orders.order',
                        verbose_name='订单',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='return_requests',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='用户',
                    ),
                ),
                (
                    'processed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='processed_returns',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='处理人',
                    ),
                ),
            ],
            options={
                'verbose_name': '退货申请',
                'verbose_name_plural': '退货申请',
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='orders_retu_status_4b7c21_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', 'created_at'], name='orders_retu_user_id_7a5c18_idx'),
        ),
    ]

