# Generated by Django 5.2.7 on 2025-12-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_returnrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='returnrequest',
            new_name='orders_retu_status_1e9e5b_idx',
            old_name='orders_retu_status_4b7c21_idx',
        ),
        migrations.RenameIndex(
            model_name='returnrequest',
            new_name='orders_retu_user_id_41b529_idx',
            old_name='orders_retu_user_id_7a5c18_idx',
        ),
    ]
