# Generated by Django 5.2.7 on 2025-12-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_orders_retu_status_4b7c21_idx_orders_retu_status_1e9e5b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='logistics_company',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='logistics_company',
        ),
    ]
