# Generated by Django 5.2.7 on 2025-12-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='snapshot_city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_province',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot_town',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='县/街道'),
        ),
    ]
