# Generated by Django 5.2.7 on 2025-02-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_productsku'),
        ('orders', '0019_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('sku_specs', models.JSONField(blank=True, default=dict, verbose_name='规格信息')),
                ('sku_code', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU编码')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('snapshot_image', models.URLField(blank=True, default='', max_length=500, verbose_name='商品主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='产品')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
            },
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.productsku', verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'sku')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_8e7516_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_69a1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['sku'], name='orders_orde_sku_id_375864_idx'),
        ),
    ]
