# Generated by Django 5.2.7 on 2025-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderitem_productsku'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_5d347b_idx',
            old_name='orders_orde_order_i_8e7516_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_product_32ff41_idx',
            old_name='orders_orde_product_69a1ff_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_sku_id_fa513e_idx',
            old_name='orders_orde_sku_id_375864_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='orders_refu_status_b87fcd_idx',
            old_name='orders_refu_status_b5d603_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='orders_refu_order_i_341cd7_idx',
            old_name='orders_refu_order_i_268222_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='orders_refu_payment_32acb6_idx',
            old_name='orders_refu_payment_08a08a_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='orders_refu_created_8e3279_idx',
            old_name='orders_refu_created_6d1cd2_idx',
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
