# Generated by Django 5.2.7 on 2026-01-17 17:12

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_rename_orders_orde_order_i_8e7516_idx_orders_orde_order_i_5d347b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(
                choices=[('amount', '减免金额'), ('percent', '折扣率')],
                default='amount',
                max_length=20,
                verbose_name='折扣类型',
            ),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='折扣值',
            ),
        ),
    ]
