# Generated by Codex on 2026-01-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_haier_fail_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShippingSync',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待同步'), ('succeeded', '同步成功'), ('failed', '同步失败')], default='pending', max_length=20, verbose_name='同步状态')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='请求数据')),
                ('response', models.JSONField(blank=True, default=dict, verbose_name='响应数据')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_syncs', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '发货同步记录',
                'verbose_name_plural': '发货同步记录',
                'indexes': [
                    models.Index(fields=['order']),
                    models.Index(fields=['status']),
                    models.Index(fields=['next_retry_at']),
                ],
            },
        ),
    ]
