# Generated by Codex on 2026-02-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_shipping_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='发货信息'),
        ),
    ]
