# Generated by Django 5.2.7 on 2026-04-02 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_homebanner_position'),
        ('orders', '0026_order_shipping_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('main', '主订单'), ('haier', '海尔子订单'), ('local', '本地子订单')], default='main', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_orders', to='orders.order', verbose_name='主订单'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='receive_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='签收数量'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reject_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='拒收数量'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='退货数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='haier_so_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='海尔子订单号'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['parent_order'], name='orders_orde_parent__e968fb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_orde_order_t_d697ad_idx'),
        ),
    ]
