# Generated by Django 5.2.7 on 2026-06-05 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_order_type_order_parent_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShippingAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ship', '发货'), ('cancel_shipping', '取消发货'), ('reship', '重新发货')], max_length=30, verbose_name='操作')),
                ('status', models.CharField(choices=[('succeeded', '成功'), ('failed', '失败')], max_length=20, verbose_name='结果')),
                ('shipping_snapshot', models.JSONField(blank=True, default=dict, verbose_name='物流快照')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='原因')),
                ('wechat_sync_required', models.BooleanField(default=False, verbose_name='需要同步微信')),
                ('wechat_synced', models.BooleanField(default=False, verbose_name='微信同步成功')),
                ('wechat_response', models.JSONField(blank=True, default=dict, verbose_name='微信响应摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_actions', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '发货操作记录',
                'verbose_name_plural': '发货操作记录',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_ship_action_order_idx'), models.Index(fields=['action', 'status'], name='orders_ship_action_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('action', 'cancel_shipping'), ('status', 'succeeded')), fields=('order',), name='uniq_success_cancel_shipping')],
            },
        ),
    ]
