# Generated by Django 5.2.7 on 2026-05-05 04:39

import django.db.models.deletion
import stores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_remove_category_unique_category_level_parent_name_and_more'),
        ('orders', '0027_order_order_type_order_parent_order_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=stores.models.get_main_store_pk, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='orders_orde_store_i_610c63_idx'),
        ),
    ]
