# Generated by Django 5.2.7 on 2026-05-07 09:52

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_specialzoneproduct_specialzone_and_more'),
        ('orders', '0028_order_store_order_orders_orde_store_i_610c63_idx'),
        ('stores', '0002_store_marketplace_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suborder_number', models.CharField(default=orders.models.generate_order_number, max_length=100, unique=True, verbose_name='子单号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '待发货'), ('shipped', '待收货'), ('completed', '已完成'), ('cancelled', '已取消'), ('returning', '退货中'), ('refunding', '退款中'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='子单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '子单',
                'verbose_name_plural': '子单',
            },
        ),
        migrations.CreateModel(
            name='SubOrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('sku_specs', models.JSONField(blank=True, default=dict, verbose_name='规格信息')),
                ('sku_code', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU编码')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('snapshot_image', models.URLField(blank=True, default='', max_length=500, verbose_name='商品主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '子单商品',
                'verbose_name_plural': '子单商品',
            },
        ),
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkout_number', models.CharField(default=orders.models.generate_order_number, max_length=100, unique=True, verbose_name='结算单号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunding', '退款中'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='结算状态')),
                ('payment_status', models.CharField(choices=[('init', '待支付'), ('processing', '支付中'), ('succeeded', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('expired', '已过期')], default='init', max_length=20, verbose_name='支付状态')),
                ('payment_number', models.CharField(blank=True, default='', max_length=100, verbose_name='支付单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('snapshot_contact_name', models.CharField(default='', max_length=50, verbose_name='联系人')),
                ('snapshot_phone', models.CharField(default='', max_length=20, verbose_name='手机号')),
                ('snapshot_address', models.TextField(default='', verbose_name='收货地址')),
                ('snapshot_province', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='省')),
                ('snapshot_city', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='市')),
                ('snapshot_district', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='区')),
                ('snapshot_town', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='县/街道')),
                ('note', models.TextField(blank=True, default='', verbose_name='用户备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '结算单',
                'verbose_name_plural': '结算单',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.checkoutorder', verbose_name='结算单'),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.checkoutorder', verbose_name='结算单'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['checkout_order'], name='orders_orde_checkou_6e5790_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_order'], name='orders_paym_checkou_f8df47_idx'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='checkout_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suborders', to='orders.checkoutorder', verbose_name='结算单'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='legacy_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='suborder_record', to='orders.order', verbose_name='兼容订单'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suborders', to='catalog.product', verbose_name='商品SPU'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suborders', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suborders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='suborderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suborder_items', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='suborderitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suborder_items', to='catalog.productsku', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='suborderitem',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.suborder', verbose_name='子单'),
        ),
        migrations.AddIndex(
            model_name='checkoutorder',
            index=models.Index(fields=['user', 'created_at'], name='orders_chec_user_id_4e9204_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutorder',
            index=models.Index(fields=['status'], name='orders_chec_status_93529e_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutorder',
            index=models.Index(fields=['payment_status'], name='orders_chec_payment_1e2aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='suborder',
            index=models.Index(fields=['checkout_order'], name='orders_subo_checkou_86c74f_idx'),
        ),
        migrations.AddIndex(
            model_name='suborder',
            index=models.Index(fields=['user', 'created_at'], name='orders_subo_user_id_3daca5_idx'),
        ),
        migrations.AddIndex(
            model_name='suborder',
            index=models.Index(fields=['store', 'status'], name='orders_subo_store_i_972d05_idx'),
        ),
        migrations.AddIndex(
            model_name='suborder',
            index=models.Index(fields=['product'], name='orders_subo_product_53f695_idx'),
        ),
        migrations.AddIndex(
            model_name='suborderitem',
            index=models.Index(fields=['suborder'], name='orders_subo_suborde_2002b1_idx'),
        ),
        migrations.AddIndex(
            model_name='suborderitem',
            index=models.Index(fields=['product'], name='orders_subo_product_c84553_idx'),
        ),
        migrations.AddIndex(
            model_name='suborderitem',
            index=models.Index(fields=['sku'], name='orders_subo_sku_id_638670_idx'),
        ),
    ]
