# Generated by Django 5.2.7 on 2025-11-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='haier', help_text='配置标识，默认为haier', max_length=50, unique=True, verbose_name='配置名称')),
                ('config', models.JSONField(help_text='海尔API配置，包含client_id、client_secret等', verbose_name='配置信息')),
                ('is_active', models.BooleanField(default=True, help_text='禁用后将不会使用此配置', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '海尔API配置',
                'verbose_name_plural': '海尔API配置',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HaierSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('products', '商品同步'), ('prices', '价格同步'), ('stock', '库存同步'), ('order', '订单推送'), ('logistics', '物流查询'), ('manual', '手动操作')], db_index=True, max_length=20, verbose_name='同步类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], db_index=True, default='pending', max_length=20, verbose_name='同步状态')),
                ('message', models.TextField(blank=True, help_text='同步过程中的详细信息或错误信息', verbose_name='同步消息')),
                ('total_count', models.IntegerField(default=0, help_text='处理的总记录数', verbose_name='总数')),
                ('success_count', models.IntegerField(default=0, help_text='成功处理的记录数', verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, help_text='失败的记录数', verbose_name='失败数')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '海尔同步日志',
                'verbose_name_plural': '海尔同步日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SupplierConfig',
        ),
        migrations.DeleteModel(
            name='SupplierSyncLog',
        ),
        migrations.AddIndex(
            model_name='haiersynclog',
            index=models.Index(fields=['status', '-created_at'], name='integration_status_b1388a_idx'),
        ),
        migrations.AddIndex(
            model_name='haiersynclog',
            index=models.Index(fields=['sync_type', '-created_at'], name='integration_sync_ty_0bd069_idx'),
        ),
    ]
