# Generated by Django 5.2.7 on 2025-12-03 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support/attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['attachment_type'], name='support_sup_attachm_54bc2a_idx'),
        ),
    ]
