# Generated by Django 5.2.7 on 2025-12-03 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_homebanner_image_alter_inventorylog_product'),
        ('orders', '0018_alter_cart_user_alter_cartitem_cart_and_more'),
        ('support', '0002_supportmessage_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['order'], name='support_sup_order_i_c35c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['product'], name='support_sup_product_cd2223_idx'),
        ),
    ]
