# Generated by Django 5.2.7 on 2026-02-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_supportconversation_last_user_entered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('first_contact', '首次联系'), ('idle_contact', '长时间未联系'), ('both', '首次联系 + 长时间未联系')], max_length=20, null=True),
        ),
    ]
