# Generated by Django 5.2.7 on 2026-05-10 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_product_specifications'),
        ('orders', '0029_checkout_suborders'),
        ('support', '0009_alter_supportreplytemplate_trigger_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportconversation',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '客服会话', 'verbose_name_plural': '客服会话'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': '客服消息', 'verbose_name_plural': '客服消息'},
        ),
        migrations.AlterModelOptions(
            name='supportreplytemplate',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '客服回复模板', 'verbose_name_plural': '客服回复模板'},
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='first_contacted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次联系时间'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='last_auto_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后自动回复时间'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='last_support_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='客服最后消息时间'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='last_user_entered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='用户最后进入时间'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='用户最后消息时间'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='supportconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support/attachments/%Y/%m/%d/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', '图片'), ('video', '视频')], db_index=True, max_length=10, null=True, verbose_name='附件类型'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='content',
            field=models.TextField(blank=True, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='content_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='内容配置'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='content_type',
            field=models.CharField(default='text', max_length=20, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportconversation', verbose_name='会话'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='orders.order', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='catalog.product', verbose_name='关联商品'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='role',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='发送角色'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送人'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='support.supportreplytemplate', verbose_name='关联模板'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='apply_channels',
            field=models.JSONField(blank=True, default=list, verbose_name='适用渠道'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='apply_user_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='适用用户标签'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='content',
            field=models.TextField(verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='content_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='内容配置'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='content_type',
            field=models.CharField(choices=[('text', '纯文本'), ('card', '图文卡片'), ('quick_buttons', '快捷问题按钮')], default='text', max_length=20, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='daily_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='每日发送上限'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='分组名称'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='idle_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='闲置分钟数'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='template_type',
            field=models.CharField(choices=[('auto', '自动回复'), ('quick', '快捷回复')], default='quick', max_length=20, verbose_name='模板类型'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='title',
            field=models.CharField(max_length=120, verbose_name='模板标题'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('first_contact', '首次联系'), ('idle_contact', '长时间未联系'), ('both', '首次联系 + 长时间未联系')], max_length=20, null=True, verbose_name='触发事件'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='使用次数'),
        ),
        migrations.AlterField(
            model_name='supportreplytemplate',
            name='user_cooldown_days',
            field=models.PositiveIntegerField(default=1, verbose_name='用户冷却天数'),
        ),
    ]
