# Generated by Codex on 2026-06-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_sub_admin_permissions'),
        ('support', '0010_alter_supportconversation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='工单编号')),
                ('ticket_type', models.CharField(choices=[('question', '问题'), ('requirement', '需求')], default='question', max_length=20, verbose_name='工单类型')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='图片附件')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('replied', '已回复'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('last_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='最后回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_tickets', to='stores.store', verbose_name='店铺')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '问题建议工单',
                'verbose_name_plural': '问题建议工单',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackTicketReply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('user_supplement', '用户补充'), ('merchant_reply', '商家回复'), ('close', '工单关闭')], max_length=20, verbose_name='记录类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='图片附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_ticket_replies', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.feedbackticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '问题建议处理记录',
                'verbose_name_plural': '问题建议处理记录',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['ticket_number'], name='fb_ticket_no_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['store', 'status'], name='fb_ticket_store_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['user', 'created_at'], name='fb_ticket_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['status', 'created_at'], name='fb_ticket_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticketreply',
            index=models.Index(fields=['ticket', 'created_at'], name='fb_reply_ticket_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackticketreply',
            index=models.Index(fields=['record_type'], name='fb_reply_type_idx'),
        ),
    ]
