# Generated by Django 5.2.7 on 2026-05-10 11:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_marketplace_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-is_main', 'id'], 'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
        migrations.AlterModelOptions(
            name='storemember',
            options={'verbose_name': '店铺成员', 'verbose_name_plural': '店铺成员'},
        ),
        migrations.AlterModelOptions(
            name='storepaymentconfig',
            options={'verbose_name': '店铺支付配置', 'verbose_name_plural': '店铺支付配置'},
        ),
        migrations.AlterModelOptions(
            name='storesettlementrule',
            options={'verbose_name': '店铺结算规则', 'verbose_name_plural': '店铺结算规则'},
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='store',
            name='allow_haier',
            field=models.BooleanField(default=False, verbose_name='启用海尔能力'),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.SlugField(max_length=64, unique=True, verbose_name='店铺编码'),
        ),
        migrations.AlterField(
            model_name='store',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover_image',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='店铺简介'),
        ),
        migrations.AlterField(
            model_name='store',
            name='home_order',
            field=models.IntegerField(default=0, verbose_name='首页排序'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='是否主店'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='店铺Logo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='store',
            name='platform_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_stores', to='stores.store', verbose_name='所属平台店铺'),
        ),
        migrations.AlterField(
            model_name='store',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='首页展示'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('self_operated', '自营店铺'), ('partner', '合作方店铺'), ('supplier', '供应商')], default='self_operated', max_length=32, verbose_name='店铺类型'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='storemember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storemember',
            name='role',
            field=models.CharField(choices=[('platform_admin', '平台管理员'), ('store_admin', '店铺管理员'), ('store_staff', '店铺运营')], default='store_staff', max_length=32, verbose_name='成员角色'),
        ),
        migrations.AlterField(
            model_name='storemember',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='storemember',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='storemember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='storemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='storepaymentconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storepaymentconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='storepaymentconfig',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_config', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='storepaymentconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='storepaymentconfig',
            name='wechat_mch_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='微信商户号'),
        ),
        migrations.AlterField(
            model_name='storepaymentconfig',
            name='wechat_sub_mch_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='微信子商户号'),
        ),
        migrations.AlterField(
            model_name='storesettlementrule',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='佣金比例'),
        ),
        migrations.AlterField(
            model_name='storesettlementrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='storesettlementrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='storesettlementrule',
            name='settlement_cycle_days',
            field=models.PositiveIntegerField(default=7, verbose_name='结算周期天数'),
        ),
        migrations.AlterField(
            model_name='storesettlementrule',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_rule', to='stores.store', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='storesettlementrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
