# Generated by Django 6.0.5 on 2026-05-29 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_activity_home_store_cards'),
        ('stores', '0004_store_sub_admin_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='show_customer_group_name',
            field=models.BooleanField(default=False, verbose_name='小程序展示客户分组名称'),
        ),
        migrations.CreateModel(
            name='StoreCustomerGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='分组说明')),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_groups', to='stores.store', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '店铺客户分组',
                'verbose_name_plural': '店铺客户分组',
                'ordering': ['store_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreCustomerGroupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='手机号')),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='stores.storecustomergroup', verbose_name='客户分组')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_group_members', to='stores.store', verbose_name='店铺')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_customer_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='小程序用户')),
            ],
            options={
                'verbose_name': '店铺客户归组',
                'verbose_name_plural': '店铺客户归组',
                'ordering': ['store_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreCustomerGroupPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='分组价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='stores.storecustomergroup', verbose_name='客户分组')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_group_prices', to='catalog.product', verbose_name='商品')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_group_prices', to='catalog.productsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '店铺客户分组价格',
                'verbose_name_plural': '店铺客户分组价格',
                'ordering': ['group_id', 'product_id', 'sku_id'],
            },
        ),
        migrations.AddIndex(
            model_name='storecustomergroup',
            index=models.Index(fields=['store', 'status'], name='stores_stor_store_i_6fc81b_idx'),
        ),
        migrations.AddConstraint(
            model_name='storecustomergroup',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='stores_unique_customer_group_name'),
        ),
        migrations.AddIndex(
            model_name='storecustomergroupmember',
            index=models.Index(fields=['store', 'status'], name='stores_stor_store_i_7d327d_idx'),
        ),
        migrations.AddIndex(
            model_name='storecustomergroupmember',
            index=models.Index(fields=['phone'], name='stores_stor_phone_7c34ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='storecustomergroupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('store', 'user'), name='stores_unique_customer_group_member_user'),
        ),
        migrations.AddConstraint(
            model_name='storecustomergroupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('store', 'phone'), name='stores_unique_customer_group_member_phone'),
        ),
        migrations.AddIndex(
            model_name='storecustomergroupprice',
            index=models.Index(fields=['group', 'product'], name='stores_stor_group_i_3c4ade_idx'),
        ),
        migrations.AddIndex(
            model_name='storecustomergroupprice',
            index=models.Index(fields=['sku'], name='stores_stor_sku_id_847952_idx'),
        ),
        migrations.AddConstraint(
            model_name='storecustomergroupprice',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', True)), fields=('group', 'product'), name='stores_unique_group_product_price'),
        ),
        migrations.AddConstraint(
            model_name='storecustomergroupprice',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('group', 'sku'), name='stores_unique_group_sku_price'),
        ),
    ]
