# Generated by Django 5.2.7 on 2025-11-03 09:10

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=users.models.generate_unique_username, max_length=150, verbose_name='用户名'),
        ),
    ]
