# Generated by Django 5.2.7 on 2025-11-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y', verbose_name='头像链接'),
        ),
    ]
