# Generated by Django 5.2.7 on 2025-11-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('wechat', '微信用户'), ('admin', '管理员')], default='wechat', max_length=20, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
