# Generated by Django 5.2.7 on 2025-11-15 15:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_last_login_at_user_user_type_alter_user_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=users.models.generate_unique_username, max_length=150, unique=True, verbose_name='用户名'),
        ),
    ]
