# Generated by Django 5.2.7 on 2025-11-28 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', '个人用户'), ('dealer', '经销商')], default='individual', max_length=20, verbose_name='用户角色'),
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('business_license', models.CharField(max_length=100, unique=True, verbose_name='营业执照号')),
                ('legal_representative', models.CharField(max_length=50, verbose_name='法人代表')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('district', models.CharField(max_length=20, verbose_name='区县')),
                ('detail_address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('business_scope', models.TextField(blank=True, verbose_name='经营范围')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'indexes': [models.Index(fields=['business_license'], name='users_compa_busines_ebf36a_idx'), models.Index(fields=['status'], name='users_compa_status_b36e98_idx')],
            },
        ),
    ]
