# Generated by Django 5.2.7 on 2025-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_role_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='detail_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='district',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='区县'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='province',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='省份'),
        ),
    ]
