# Generated by Django 5.2.7 on 2025-11-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_companyinfo_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', '个人用户'), ('dealer', '经销商'), ('admin', '管理员')], default='individual', max_length=20, verbose_name='用户角色'),
        ),
    ]
