# Generated by Django 5.2.7 on 2025-11-28 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_user_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='账期开始日期')),
                ('period_end', models.DateField(verbose_name='账期结束日期')),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='上期结余')),
                ('current_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本期采购')),
                ('current_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本期付款')),
                ('current_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本期退款')),
                ('period_end_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='期末未付')),
                ('due_within_term', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='账期内应付')),
                ('paid_within_term', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='账期内已付')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='往来余额（逾期）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('settled', '已结清')], default='draft', max_length=20, verbose_name='对账单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结清时间')),
            ],
            options={
                'verbose_name': '账务对账单',
                'verbose_name_plural': '账务对账单',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='信用额度')),
                ('payment_term_days', models.IntegerField(default=30, verbose_name='账期（天）')),
                ('outstanding_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='未结清欠款')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL, verbose_name='经销商用户')),
            ],
            options={
                'verbose_name': '信用账户',
                'verbose_name_plural': '信用账户',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', '采购'), ('payment', '付款'), ('refund', '退款'), ('adjustment', '调整')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易金额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易后余额')),
                ('order_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联订单ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='应付日期')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='实付日期')),
                ('payment_status', models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款'), ('overdue', '已逾期')], default='unpaid', max_length=20, verbose_name='付款状态')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.accountstatement', verbose_name='关联对账单')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.creditaccount', verbose_name='信用账户')),
            ],
            options={
                'verbose_name': '账务交易记录',
                'verbose_name_plural': '账务交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='users.creditaccount', verbose_name='信用账户'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['user'], name='users_credi_user_id_30a8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['is_active'], name='users_credi_is_acti_b52898_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['credit_account', 'created_at'], name='users_accou_credit__3a12ac_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['transaction_type'], name='users_accou_transac_4311e0_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['payment_status'], name='users_accou_payment_5a9b03_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['due_date'], name='users_accou_due_dat_77ce82_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstatement',
            index=models.Index(fields=['credit_account', 'period_start', 'period_end'], name='users_accou_credit__b8a7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstatement',
            index=models.Index(fields=['status'], name='users_accou_status_2b2d9a_idx'),
        ),
    ]
