# Generated by Django 5.2.7 on 2025-12-02 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_accountstatement_creditaccount_accounttransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatement',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='users.creditaccount', verbose_name='信用账户'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.creditaccount', verbose_name='信用账户'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_info', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.PROTECT, related_name='credit_account', to=settings.AUTH_USER_MODEL, verbose_name='经销商用户'),
        ),
    ]
