# Generated by Django 5.2.7 on 2025-12-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_accountstatement_credit_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', '个人用户'), ('dealer', '经销商'), ('support', '客服'), ('admin', '管理员')], default='individual', max_length=20, verbose_name='用户角色'),
        ),
    ]
