# Generated by Django 5.2.7 on 2025-12-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
        ('users', '0016_alter_user_role'),
    ]

    operations = [
    ]
