# Generated by Django 5.2.7 on 2025-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification_read_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_user_id_9d0e22_idx',
            old_name='users_notif_user_id__25c28a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_type_0792c9_idx',
            old_name='users_notif_type_1d15b6_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_created_3ee999_idx',
            old_name='users_notif_created_6e8225_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_read_at_d5f310_idx',
            old_name='users_not_read_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment', '支付'), ('order', '订单'), ('refund', '退款'), ('return', '退货'), ('statement', '对账单'), ('system', '系统')], default='system', max_length=20, verbose_name='类型'),
        ),
    ]
