# Generated by Django 5.2.7 on 2026-01-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_users_notif_user_id__25c28a_idx_users_notif_user_id_9d0e22_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='reject_reason',
            field=models.TextField(blank=True, default='', verbose_name='拒绝原因'),
        ),
    ]
