# Generated by Django 5.2.7 on 2026-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_companyinfo_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '待审核'),
                    ('withdrawn', '已撤回'),
                    ('approved', '已审核'),
                    ('rejected', '已拒绝'),
                ],
                default='pending',
                max_length=20,
                verbose_name='审核状态',
            ),
        ),
    ]
